### ISSUE TITLE
update installer scripts

### ISSUE THREAD

**Issue by lufre1** [computational-cell-analytics/micro-sam#505]
## Description
Update installer scripts and make new release.

## ToDo
- [x] disable mac support
- [ ] check source branches
- [x] check triggers (git tags)
- [ ] run workflow
- [ ] check installers

## Solutions
- source branch:
  - as long as nothing is specified, then `default` branch is source branch
    - for now, the `default` branch is `master`
  - here is how to specify a branch:
```yaml
steps:
  - name: Checkout specific branch
    uses: actions/checkout@v4
    with:
      branch: 'feature/my-new-feature'  # Replace with desired branch name
```
or checkout the branch that contains the tagged commit:
```yaml
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }} 
```
- triggers:
  - atm any tag triggers the workflow
    - tags 
  - specify pushes to branch as trigger
```yaml
on:
  push:
    branches:
      - 'master'  
    tags:
      - '**'
```
-
